# Generated by Django 4.0 on 2021-12-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='dadname',
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
