# Generated by Django 4.0 on 2021-12-12 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_phonenumbers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid', regex='\\b\\w{0,15}\\b')], verbose_name='name'),
        ),
    ]
