# Generated by Django 4.0 on 2021-12-12 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_phonenumbers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid', message='Error, invalid data', regex='[A-ZА-Я]{1}[A-Za-zА-Яа-я]{1,14}$')], verbose_name='name'),
        ),
    ]
