# Generated by Django 4.0 on 2021-12-12 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_phonenumbers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid', message='Error, invalid data', regex='[A-ZА-Я]{1}[a-zа-я]{1,14}$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid', message='Error, invalid data', regex='\\d{11}')], verbose_name='phonenumber'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='secname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Invalid', message='Error, invalid data', regex='[A-ZА-Я]{1}[a-zа-я]{1,19}$')], verbose_name='secname'),
        ),
    ]
