# Generated by Django 4.0 on 2021-12-14 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_phonenumbers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid', message='Ошибка, некорректное имя', regex='[A-ZА-Я]{1}[a-zа-я]{1,14}$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid', message='Ошибка, некорректный номер телефона', regex='[0-9]{11}')], verbose_name='phonenumber'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='secname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Invalid', message='Ошибка, некорректная фамилия', regex='[A-ZА-Я]{1}[a-zа-я]{1,19}$')], verbose_name='secname'),
        ),
    ]
