# Generated by Django 4.0 on 2021-12-14 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_phonenumbers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid', message='Ошибка, некорректный номер телефона', regex='[0-9]{11,11}')], verbose_name='phonenumber'),
        ),
    ]
