# Generated by Django 4.0 on 2021-12-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_phonenumbers_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phonenumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid', message='Ошибка, некорректный номер телефона', regex='[0-9]{11}')], verbose_name='phonenumber'),
        ),
    ]
